version: '3'

services:
  db:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: ong
      MYSQL_USER: root@localhost 
      MYSQL_PASSWORD: 1234
    volumes:
      - ./data:/var/lib/mysql
    ports:
      - 3307:3306